"""empty message

Revision ID: eb9e79df6584
Revises: 0f35a16ff79a
Create Date: 2022-09-27 10:10:10.483894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'eb9e79df6584'
down_revision = '0f35a16ff79a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    accounttype = postgresql.ENUM('FREE', 'PREMIUM', name='accounttype')
    accounttype.create(op.get_bind())

    op.add_column('users', sa.Column('account_type', sa.Enum('FREE', 'PREMIUM', name='accounttype'), nullable=True))
    op.add_column('users', sa.Column('subscribed_due', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscribed_due')
    op.drop_column('users', 'account_type')
    # ### end Alembic commands ###
